use hello-world as demo
laincloud/white-paper pull request #51
Opened 2017-05-23 08:06 UTC by bibaijin

2017-05-25 07:07 UTC, liuxu623 approved these changes

2017-05-25 08:24 UTC, liuxu623 commented on install/lain-client.md
> +docker daemon 的 `insecure-registries` 选项。例如，在 Linux 上，可以将 `/etc/docker/daemon.json` 改为：
这里最好也说下macOS的配置方法，开发环境用macOS的应该多一些

2017-05-25 08:26 UTC, liuxu623 commented on install/lain-client.md
> +
这里要说下为什么需要共享这个目录，这个目录涉及macOS的系统文件，能不能不共享这个目录

2017-05-25 08:31 UTC, liuxu623 requested changes
1.需要添加 macOS 配置 insecure registry
2.说明为什么需要共享/var/folders目录

2017-05-25 08:31 UTC, liuxu623 approved these changes

2017-05-26 01:45 UTC, bibaijin commented on install/lain-client.md
> +
[这个目录是 macOS 的临时文件目录](http://www.magnusviri.com/Mac/what-is-var-folders.html)，是 python 的 tempfile.mkdtemp() 函数生成的。我理解 tempfile 已经为不同的操作系统做了兼容性处理，如果我们指定 prefix，那 Linux 和 Windows 的目录结构不一样，就会导致兼容性问题。虽然我们没有在 windows 上做过测试，但似乎不应该故意引入不兼容的修改。

2017-05-26 02:38 UTC, bibaijin commented on install/lain-client.md
> +docker daemon 的 `insecure-registries` 选项。例如，在 Linux 上，可以将 `/etc/docker/daemon.json` 改为：
- 已经添加 macOS 的截图
- 当时也想用添加，感觉也不合适，因为 `{ insecure-registries: ` 这部分可能原来已经有了，所以改成了示例的方式，你看是否合适？

2017-05-26 02:40 UTC, bibaijin commented on install/lain-client.md
> +
- 已经在文中说明需要共享这个目录的原因
- 感觉让 macOS 配置共享目录比更改代码更合适的原因见上条回复~

2017-05-26 02:45 UTC, bibaijin commented
- 已添加 macOS 配置 Insecure Registries 和 File Sharing 的截图
- 已添加共享 /var/folders 目录的说明

2017-06-02 14:21 UTC, bibaijin commented
- 已更改关于安装 lain-cli 的说明
- 已添加 git commit 的说明
@fossilet

2017-06-05 05:38 UTC, fossilet approved these changes

2017-06-05 05:41 UTC, merged