Update github refs.
laincloud/white-paper pull request #71
Opened 2017-08-09 07:08 UTC by fossilet

2017-08-10 12:19 UTC, fossilet commented
@bibaijin 检查一下原来的tag，在这标注一下吧。

2017-08-10 12:22 UTC, bibaijin commented
好~ @fossilet

2017-08-11 03:12 UTC, bibaijin requested changes

2017-08-11 03:12 UTC, bibaijin commented on tutorial/lain-yaml-more.md
> +[laincloud/hello-world/lain.yaml@master](https://github.com/laincloud/hello-world/blob/master/lain.yaml)
这里需要改为 service

2017-08-11 03:12 UTC, bibaijin commented on tutorial/service-demo.md
> +[laincloud/hello-world@master](https://github.com/laincloud/hello-world/tree/master) 的完整代码在这里。
这里需要改为 service

2017-08-11 06:16 UTC, bibaijin approved these changes

2017-08-11 06:16 UTC, merged